[package]
name = "ferrogallic_web"
version = "0.0.0"
authors = ["Erik Desjardins <erikdesjardins@users.noreply.github.com>"]
description = "Clone of skribble.io."
repository = "https://github.com/erikdesjardins/ferrogallic"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ferrogallic_api = { path = "../ferrogallic_api" }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wee_alloc = "0.4.2"
