name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*.*.*
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: rustup component add rustfmt

    - run: cargo fmt --manifest-path ferrogallic/Cargo.toml -- --check
    - run: cargo fmt --manifest-path ferrogallic_api/Cargo.toml -- --check
    - run: cargo fmt --manifest-path ferrogallic_web/Cargo.toml -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: rustup component add clippy
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - run: wasm-pack build --dev --target web ferrogallic_web
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path ferrogallic/Cargo.toml
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path ferrogallic_api/Cargo.toml
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path ferrogallic_web/Cargo.toml

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - run: wasm-pack build --dev --target web ferrogallic_web
    - run: cargo test --manifest-path ferrogallic/Cargo.toml
    - run: cargo test --manifest-path ferrogallic_api/Cargo.toml
    - run: cargo test --manifest-path ferrogallic_web/Cargo.toml

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - run: wasm-pack build --release --target web ferrogallic_web
    - run: cargo build --release --manifest-path ferrogallic/Cargo.toml
    - run: strip ferrogallic/target/release/ferrogallic
    - run: ls -lh ferrogallic/target/release/ferrogallic

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ferrogallic/target/release/ferrogallic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
