name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*.*.*
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: rustup component add rustfmt

    - run: cargo fmt --manifest-path ferrogallic/Cargo.toml -- --check
      if: "!cancelled()"
    - run: cargo fmt --manifest-path ferrogallic_shared/Cargo.toml -- --check
      if: "!cancelled()"
    - run: cargo fmt --manifest-path ferrogallic_web/Cargo.toml -- --check
      if: "!cancelled()"

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: rustup component add clippy
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - run: wasm-pack build --dev --target web ferrogallic_web
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path ferrogallic/Cargo.toml
      if: "!cancelled()"
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path ferrogallic_shared/Cargo.toml
      if: "!cancelled()"
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path ferrogallic_web/Cargo.toml
      if: "!cancelled()"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - run: wasm-pack build --dev --target web ferrogallic_web
    - run: cargo test --manifest-path ferrogallic/Cargo.toml
      if: "!cancelled()"
    - run: cargo test --manifest-path ferrogallic_shared/Cargo.toml
      if: "!cancelled()"
    - run: wasm-pack test --chrome --headless ferrogallic_web
      if: "!cancelled()"

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - run: wasm-pack build --release --target web ferrogallic_web
    - run: ls -lh ferrogallic_web/pkg/ferrogallic_web_bg.wasm
    - run: cargo build --release --manifest-path ferrogallic/Cargo.toml --target=x86_64-unknown-linux-musl
    - run: strip ferrogallic/target/x86_64-unknown-linux-musl/release/ferrogallic
    - run: ls -lh ferrogallic/target/x86_64-unknown-linux-musl/release/ferrogallic

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ferrogallic/target/x86_64-unknown-linux-musl/release/ferrogallic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
